name: ubuntu18.04-build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: MIN-Group/minlib
          ref: main
          path: miblib

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install Dependency Library
        run: ./install.sh

      - name: Test
        run: go test -v ./...
